#!/usr/bin/env python3
"""Read-only evidence probe for the Phase 1 target perimeter.

The probe can prove properties of the machine from which it is run (for
example, that this source address is inside an operator-supplied CIDR and that
an HTTP endpoint accepts a read-only connection).  It deliberately cannot
prove that an *outside* network cannot connect.  That assertion is accepted
only when a separately collected, signed/attested evidence file is supplied;
the file is never generated by this script.

The command exits zero only for an overall ``PASS``.  Missing external evidence
and hard probe failures produce ``NOT_PROVEN`` in the machine-readable output.
No request made by this script mutates platform state: it uses GET/HEAD-style
read-only requests only.
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import socket
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

OK_STATUS = "PASS"
ERROR_STATUS = "FAIL"
UNPROVEN_STATUS = "NOT_PROVEN"
DEFAULT_TIMEOUT = 5.0
FORBIDDEN_ROUTE_SEGMENTS = {"login", "users", "roles", "rbac", "memberships"}


@dataclass(frozen=True)
class Check:
    name: str
    status: str
    detail: str
    evidence: dict[str, Any]


def parse_cidrs(values: list[str]) -> list[ipaddress._BaseNetwork]:
    if not values:
        raise ValueError("at least one --allowed-cidr is required")
    return [ipaddress.ip_network(value, strict=False) for value in values]


def source_ip_for_target(host: str, port: int, timeout: float) -> str:
    """Return the OS-selected local source without sending an application request."""
    family = socket.AF_INET6 if ":" in host else socket.AF_INET
    with socket.socket(family, socket.SOCK_DGRAM) as probe:
        probe.settimeout(timeout)
        probe.connect((host, port))
        return str(probe.getsockname()[0])


def source_is_allowed(source_ip: str, networks: list[ipaddress._BaseNetwork]) -> bool:
    address = ipaddress.ip_address(source_ip)
    return any(address in network for network in networks)


def endpoint_url(base_url: str, suffix: str) -> str:
    parsed = urlparse(base_url)
    if (
        parsed.scheme != "http"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
    ):
        raise ValueError(
            "target URL must use http, include a host, and contain no userinfo/query/fragment"
        )
    base_path = parsed.path.rstrip("/")
    path = f"{base_path}{suffix}" if suffix.startswith("/") else f"/{suffix}"
    return parsed._replace(path=path, params="", query="", fragment="").geturl()


def _http_request(
    url: str,
    *,
    timeout: float,
    request_path: str | None = None,
) -> dict[str, Any]:
    parsed = urlparse(url)
    if (
        parsed.scheme != "http"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
    ):
        raise ValueError("perimeter endpoints must use http without userinfo/query/fragment")
    port = parsed.port or 80
    path = request_path or parsed.path or "/"
    if parsed.query:
        path += f"?{parsed.query}"
    request = (
        f"GET {path} HTTP/1.1\r\n"
        f"Host: {parsed.hostname}\r\n"
        "Connection: close\r\n"
        "User-Agent: crash-cap-phase1-perimeter-probe/1.0\r\n\r\n"
    ).encode("ascii")
    with socket.create_connection((parsed.hostname, port), timeout=timeout) as connection:
        connection.sendall(request)
        response = _read_http_response(connection)
        return {
            "status_code": response["status_code"],
            "reason": response["reason"],
            "headers": response["headers"],
            "body_prefix": response["body_prefix"],
            "body_text": response["body_text"],
        }


def _read_http_response(connection: socket.socket) -> dict[str, Any]:
    buffer = bytearray()
    while b"\r\n\r\n" not in buffer and len(buffer) < 64 * 1024:
        chunk = connection.recv(4096)
        if not chunk:
            break
        buffer.extend(chunk)
    header_end = buffer.find(b"\r\n\r\n")
    if header_end < 0:
        raise OSError("HTTP response did not contain a complete header")
    header_bytes = bytes(buffer[:header_end]).decode("iso-8859-1")
    body = bytearray(buffer[header_end + 4 :])
    while len(body) < 8 * 1024 * 1024:
        chunk = connection.recv(min(64 * 1024, 8 * 1024 * 1024 - len(body)))
        if not chunk:
            break
        body.extend(chunk)
    if len(body) >= 8 * 1024 * 1024:
        raise OSError("HTTP response body exceeds the bounded probe read")
    body_prefix = bytes(body[:512]).decode("utf-8", errors="replace")
    lines = header_bytes.split("\r\n")
    status_parts = lines[0].split(" ", 2)
    if len(status_parts) < 2 or not status_parts[1].isdigit():
        raise OSError("HTTP response status is invalid")
    headers: dict[str, str] = {}
    for line in lines[1:]:
        if ":" in line:
            key, value = line.split(":", 1)
            headers[key.strip().lower()] = value.strip()
    return {
        "status_code": int(status_parts[1]),
        "reason": status_parts[2] if len(status_parts) == 3 else "",
        "headers": headers,
        "body_prefix": body_prefix,
        "body_text": bytes(body).decode("utf-8", errors="replace"),
    }


def inspect_openapi(document: dict[str, Any]) -> list[Check]:
    checks: list[Check] = []
    paths = document.get("paths")
    if not isinstance(paths, dict):
        return [
            Check(
                "api.route_inventory",
                UNPROVEN_STATUS,
                "OpenAPI paths are unavailable",
                {},
            )
        ]
    delete_paths = sorted(
        str(path)
        for path, operations in paths.items()
        if isinstance(operations, dict)
        and "delete" in {str(method).lower() for method in operations}
    )
    if delete_paths:
        checks.append(
            Check(
                "api.no_delete",
                ERROR_STATUS,
                "DELETE routes are exposed",
                {"paths": delete_paths},
            )
        )
    else:
        checks.append(Check("api.no_delete", OK_STATUS, "OpenAPI exposes no DELETE routes", {}))

    forbidden = sorted(
        str(path)
        for path in paths
        if any(
            segment in {part for part in str(path).lower().split("/") if part}
            for segment in FORBIDDEN_ROUTE_SEGMENTS
        )
    )
    if forbidden:
        checks.append(
            Check(
                "api.no_identity_routes",
                ERROR_STATUS,
                "OpenAPI exposes login/RBAC identity routes",
                {"paths": forbidden},
            )
        )
    else:
        checks.append(
            Check(
                "api.no_identity_routes",
                OK_STATUS,
                "OpenAPI exposes no login/RBAC identity routes",
                {},
            )
        )
    checks.append(
        Check(
            "api.route_inventory",
            OK_STATUS,
            "OpenAPI route inventory was read without mutating the target",
            {"path_count": len(paths)},
        )
    )
    return checks


def load_outside_evidence(
    path: Path, api_url: str, frontend_url: str, object_store_url: str
) -> Check:
    try:
        evidence = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside-probe evidence cannot be read",
            {"path": str(path), "error": str(exc)},
        )
    if not isinstance(evidence, dict):
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside evidence must be an object",
            {},
        )
    required = ("tester", "target", "environment", "probes", "attestation")
    missing = [key for key in required if key not in evidence]
    if missing:
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside evidence is missing mandatory external metadata",
            {"missing": missing, "path": str(path)},
        )
    target = evidence["target"]
    tester = evidence["tester"]
    environment = evidence["environment"]
    attestation = evidence["attestation"]
    if not all(isinstance(item, dict) for item in (target, tester, environment, attestation)):
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside evidence metadata must be objects",
            {"path": str(path)},
        )
    expected_target = {
        "api_url": api_url,
        "frontend_url": frontend_url,
        "object_store_url": object_store_url,
    }
    if any(target.get(key) != value for key, value in expected_target.items()):
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside evidence target does not match requested endpoints",
            {"path": str(path)},
        )
    if not tester.get("name") or not isinstance(tester.get("is_developer"), bool):
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside evidence must identify a named developer or operator",
            {"path": str(path)},
        )
    if not environment.get("name") or not environment.get("observed_at"):
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside evidence must identify target environment and observation time",
            {"path": str(path)},
        )
    signature_ref = str(attestation.get("signature_ref", "")).strip()
    if not attestation.get("signed_by") or not signature_ref:
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside evidence requires an attestation reference from its actual executor",
            {"path": str(path)},
        )
    if signature_ref.lower() in {"auto", "generated", "self"}:
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside evidence cannot use an automatically generated self-signature",
            {"path": str(path)},
        )
    probes = evidence["probes"]
    if not isinstance(probes, list):
        return Check(
            "perimeter.outside_source",
            UNPROVEN_STATUS,
            "outside probes must be a list",
            {},
        )
    missing_unreachable = []
    observed_names: set[str] = set()
    for item in probes:
        if not isinstance(item, dict):
            missing_unreachable.append("<invalid>")
            continue
        source_network = str(item.get("source_network", "")).strip().lower()
        observed_names.add(str(item.get("name", "")))
        if item.get("reachable") is not False or source_network not in {
            "outside",
            "external",
            "untrusted",
        }:
            missing_unreachable.append(item.get("name", "<unnamed>"))
    missing_unreachable.extend(sorted({"api", "frontend", "object_store"} - observed_names))
    if missing_unreachable:
        return Check(
            "perimeter.outside_source",
            ERROR_STATUS,
            "outside evidence reports a reachable target or malformed probe",
            {"reachable_or_invalid": missing_unreachable, "path": str(path)},
        )
    return Check(
        "perimeter.outside_source",
        OK_STATUS,
        "outside-network probe evidence reports all target endpoints unreachable",
        {
            "path": str(path),
            "tester": tester.get("name"),
            "environment": environment.get("name"),
            "probe_count": len(probes),
            "signature_ref": attestation.get("signature_ref"),
        },
    )


def run_probe(args: argparse.Namespace) -> dict[str, Any]:
    networks = parse_cidrs(args.allowed_cidr)
    checks: list[Check] = []
    endpoints = {
        "api": (args.api_url, "/healthz"),
        "frontend": (args.frontend_url, "/"),
        "object_store": (args.object_store_url, "/health/ready"),
    }
    responses: dict[str, dict[str, Any]] = {}
    for name, (base_url, path) in endpoints.items():
        parsed = urlparse(base_url)
        if (
            parsed.scheme != "http"
            or not parsed.hostname
            or parsed.username is not None
            or parsed.password is not None
            or parsed.query
            or parsed.fragment
        ):
            checks.append(
                Check(
                    f"{name}.http",
                    ERROR_STATUS,
                    ("endpoint must be an HTTP URL with a hostname and no userinfo/query/fragment"),
                    {"url": base_url},
                )
            )
            continue
        port = parsed.port or 80
        try:
            source_ip = source_ip_for_target(parsed.hostname, port, args.timeout)
            if source_is_allowed(source_ip, networks):
                checks.append(
                    Check(
                        f"{name}.allowed_source",
                        OK_STATUS,
                        "OS-selected local source address is inside an allowed CIDR",
                        {"source_ip": source_ip, "allowed_cidrs": args.allowed_cidr},
                    )
                )
            else:
                checks.append(
                    Check(
                        f"{name}.allowed_source",
                        ERROR_STATUS,
                        "OS-selected local source address is outside allowed CIDRs",
                        {"source_ip": source_ip, "allowed_cidrs": args.allowed_cidr},
                    )
                )
            response = _http_request(endpoint_url(base_url, path), timeout=args.timeout)
            responses[name] = response
            checks.append(
                Check(
                    f"{name}.reachable",
                    OK_STATUS if 200 <= int(response["status_code"]) < 400 else ERROR_STATUS,
                    "HTTP read-only endpoint responded",
                    {"status_code": response["status_code"]},
                )
            )
        except (OSError, ValueError) as exc:
            checks.append(
                Check(
                    f"{name}.reachable",
                    UNPROVEN_STATUS,
                    "HTTP endpoint could not be probed from this source",
                    {"error_type": type(exc).__name__, "error": str(exc)},
                )
            )

    api_response = responses.get("api")
    if api_response is None:
        checks.append(
            Check(
                "api.openapi",
                UNPROVEN_STATUS,
                "API OpenAPI document was not fetched",
                {},
            )
        )
    else:
        try:
            openapi_response = _http_request(
                endpoint_url(args.api_url, "/openapi.json"),
                timeout=args.timeout,
            )
            if int(openapi_response["status_code"]) != 200:
                raise ValueError(f"OpenAPI returned HTTP {openapi_response['status_code']}")
            document = json.loads(openapi_response["body_text"])
            if not isinstance(document, dict):
                raise TypeError("OpenAPI response is not an object")
            checks.extend(inspect_openapi(document))
        except (
            OSError,
            TypeError,
            ValueError,
            json.JSONDecodeError,
        ) as exc:
            checks.append(
                Check(
                    "api.openapi",
                    UNPROVEN_STATUS,
                    "API OpenAPI document could not be inspected",
                    {"error_type": type(exc).__name__, "error": str(exc)},
                )
            )

    if args.occurrence_id:
        try:
            raw_response = _http_request(
                endpoint_url(args.api_url, f"/api/v1/occurrences/{args.occurrence_id}/download"),
                timeout=args.timeout,
            )
            body = str(raw_response["body_prefix"])
            is_disabled = (
                int(raw_response["status_code"]) == 403 and "RAW_DOWNLOAD_DISABLED" in body
            )
            checks.append(
                Check(
                    "api.raw_download_default",
                    OK_STATUS if is_disabled else ERROR_STATUS,
                    "raw download endpoint explicitly denies the supplied occurrence",
                    {
                        "status_code": raw_response["status_code"],
                        "error_code_seen": "RAW_DOWNLOAD_DISABLED" in body,
                    },
                )
            )
        except (OSError, ValueError) as exc:
            checks.append(
                Check(
                    "api.raw_download_default",
                    UNPROVEN_STATUS,
                    "raw download endpoint could not be read",
                    {"error_type": type(exc).__name__, "error": str(exc)},
                )
            )
    else:
        checks.append(
            Check(
                "api.raw_download_default",
                UNPROVEN_STATUS,
                "supply --occurrence-id to verify the default raw-download denial",
                {},
            )
        )

    if args.outside_evidence:
        checks.append(
            load_outside_evidence(
                args.outside_evidence,
                args.api_url,
                args.frontend_url,
                args.object_store_url,
            )
        )
    else:
        checks.append(
            Check(
                "perimeter.outside_source",
                UNPROVEN_STATUS,
                "no independently collected outside-probe evidence was supplied",
                {"required_argument": "--outside-evidence"},
            )
        )

    hard_failures = [check.name for check in checks if check.status == ERROR_STATUS]
    unproven = [check.name for check in checks if check.status == UNPROVEN_STATUS]
    status = OK_STATUS if not hard_failures and not unproven else UNPROVEN_STATUS
    return {
        "schema_version": "1.0",
        "status": status,
        "generated_at": datetime.now(UTC).isoformat(),
        "target": {
            "api_url": args.api_url,
            "frontend_url": args.frontend_url,
            "object_store_url": args.object_store_url,
        },
        "allowed_cidrs": args.allowed_cidr,
        "checks": [asdict(check) for check in checks],
        "hard_failures": hard_failures,
        "not_proven": unproven,
        "evidence_boundary": {
            "outside_reachability_requires_external_evidence": True,
            "local_probe_does_not_prove_global_network_unreachability": True,
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-url", required=True, help="target API HTTP base URL")
    parser.add_argument("--frontend-url", required=True, help="target Frontend HTTP base URL")
    parser.add_argument(
        "--object-store-url", required=True, help="browser-reachable RustFS HTTP base URL"
    )
    parser.add_argument(
        "--allowed-cidr",
        action="append",
        required=True,
        help="allowed source CIDR; repeatable",
    )
    parser.add_argument("--outside-evidence", type=Path)
    parser.add_argument("--occurrence-id", help="known occurrence for raw-download denial check")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT)
    parser.add_argument("--json-out", type=Path)
    args = parser.parse_args(argv)
    try:
        result = run_probe(args)
    except (OSError, ValueError) as exc:
        result = {
            "schema_version": "1.0",
            "status": UNPROVEN_STATUS,
            "generated_at": datetime.now(UTC).isoformat(),
            "checks": [
                {
                    "name": "probe.arguments",
                    "status": UNPROVEN_STATUS,
                    "detail": str(exc),
                    "evidence": {},
                }
            ],
            "hard_failures": [],
            "not_proven": ["probe.arguments"],
        }
    rendered = json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True)
    if args.json_out:
        args.json_out.write_text(rendered + "\n", encoding="utf-8")
    print(rendered)
    return 0 if result["status"] == OK_STATUS else 1


if __name__ == "__main__":
    raise SystemExit(main())
