use crate::analysis_context::{source_context_warning, AnalysisContext};
use crate::artifact::{match_artifacts, MatchInput};
use crate::canonical::{sha256_hex, CanonicalAnalysisResult, CanonicalInputs};
use crate::error::{CliError, CliResult};
use crate::minidump::{inspect_bytes, InspectFailureKind, InspectReport, MAX_DUMP_BYTES};
use crate::symbolicator::symbolicate_with_request_report;
use crate::unwind::{unwind_bytes, unwind_bytes_with_modules, UnwindReport};
use clap::{error::ErrorKind, Args, Parser, Subcommand};
use serde_json::Value;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

const EXIT_UNSUPPORTED: i32 = 2;
const EXIT_CORRUPT: i32 = 3;

#[derive(Debug, Parser)]
#[command(
    name = "dmp-core",
    version,
    about = "Crash-Cap Windows x64 minidump inspection and analysis core"
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
#[allow(clippy::large_enum_variant)]
pub enum Command {
    /// Validate a dump and extract its stable metadata streams.
    Inspect(InspectArgs),
    /// Produce a Canonical analysis result from inspect evidence.
    Analyze(AnalyzeArgs),
    /// Execute an explicitly enabled immutable Run v2 as Canonical 1.1.
    AnalyzeFrozen(crate::frozen_cli::AnalyzeFrozenArgs),
    /// Extract authoritative PE/PDB identity from verified bytes.
    Identify(IdentifyArgs),
    /// Print the core version in a script-friendly form.
    Version,
}

#[derive(Debug, Args)]
pub struct IdentifyArgs {
    /// Artifact kind (`pe` or `pdb`).
    #[arg(long, value_parser = ["pe", "pdb"])]
    pub kind: String,
    /// Input PE or PDB path.
    #[arg(long, value_name = "PATH")]
    pub artifact: PathBuf,
    /// JSON output path, or `-` for stdout.
    #[arg(long, value_name = "PATH")]
    pub output: PathBuf,
}

#[derive(Debug, Args)]
pub struct InspectArgs {
    /// Input Windows Minidump path.
    #[arg(long, value_name = "PATH")]
    pub dump: PathBuf,
    /// JSON output path, or `-` for stdout.
    #[arg(long, value_name = "PATH")]
    pub output: PathBuf,
}

#[derive(Debug, Args)]
pub struct AnalyzeArgs {
    /// Input Windows Minidump path.
    #[arg(long, value_name = "PATH")]
    pub dump: PathBuf,
    /// Inspect JSON generated by `dmp-core inspect`.
    #[arg(long, value_name = "PATH")]
    pub inspect: Option<PathBuf>,
    /// Optional artifact match JSON. Reserved for the matcher stage.
    #[arg(long = "match", value_name = "PATH")]
    pub match_file: Option<PathBuf>,
    /// Internal Symbolicator gateway endpoint.
    #[arg(long, value_name = "URL")]
    pub symbolicator: Option<String>,
    /// Workspace namespace used by Build resolution and Symbolicator scope.
    #[arg(long = "workspace-id", alias = "scope", default_value = "wsp_p0test")]
    pub workspace_id: String,
    /// Monotonic Workspace symbol inventory version used to invalidate
    /// Symbolicator's negative debug-file cache after symbols are added.
    #[arg(long, default_value_t = 0)]
    pub symbol_inventory_version: u64,
    /// Explicit capture intent. Only `hang` changes a no-exception dump to hang.
    #[arg(long, value_name = "PROFILE")]
    pub capture_profile: Option<String>,
    /// Maximum seconds for one Symbolicator request/poll cycle.
    #[arg(long, default_value_t = 30)]
    pub symbolicator_timeout: u64,
    /// Auditable OCI image digest for the core worker. Omit only for a local sentinel run.
    #[arg(long, value_name = "SHA256")]
    pub core_image_digest: Option<String>,
    /// Deployed Symbolicator version recorded by the Worker (for example 26.7.2).
    #[arg(long, value_name = "VERSION")]
    pub symbolicator_version: Option<String>,
    /// Immutable platform facts used to assemble the final Canonical v1 result.
    #[arg(long, value_name = "PATH")]
    pub analysis_context: Option<PathBuf>,
    /// Canonical JSON output path, or `-` for stdout.
    #[arg(long, value_name = "PATH")]
    pub output: PathBuf,
    /// Directory for raw engine outputs.
    #[arg(long, value_name = "PATH")]
    pub raw_dir: Option<PathBuf>,
}

pub fn parse_cli() -> CliResult<Cli> {
    match Cli::try_parse() {
        Ok(cli) => Ok(cli),
        Err(error)
            if matches!(error.kind(), ErrorKind::DisplayHelp | ErrorKind::DisplayVersion) =>
        {
            Err(CliError::new("CLI_OUTPUT", error.to_string(), 0))
        }
        Err(error) => {
            let rendered = error.render().to_string();
            Err(CliError::with_details(
                "INVALID_ARGUMENT",
                rendered.clone(),
                2,
                serde_json::json!({ "usage": rendered }),
            ))
        }
    }
}

pub fn run(cli: Cli) -> CliResult<()> {
    match cli.command {
        Command::Version => {
            println!("dmp-core {}", env!("CARGO_PKG_VERSION"));
            Ok(())
        }
        Command::Inspect(args) => run_inspect(args),
        Command::Analyze(args) => run_analyze(args),
        Command::AnalyzeFrozen(args) => crate::frozen_cli::run(args),
        Command::Identify(args) => run_identify(args),
    }
}

fn run_identify(args: IdentifyArgs) -> CliResult<()> {
    let report = crate::artifact::identify_artifact(&args.artifact, &args.kind)
        .map_err(map_artifact_error)?;
    write_json(&args.output, &report)
}

fn map_artifact_error(error: crate::artifact::ArtifactError) -> CliError {
    match error {
        crate::artifact::ArtifactError::TooLarge { path, kind, size, limit } => {
            CliError::with_details(
                "ARTIFACT_TOO_LARGE",
                format!("{kind} artifact exceeds its size limit: {}", path.display()),
                1,
                serde_json::json!({
                    "path": path,
                    "kind": kind,
                    "size": size,
                    "limit": limit,
                }),
            )
        }
        crate::artifact::ArtifactError::UnsupportedKind(kind) => CliError::with_details(
            "UNSUPPORTED_ARTIFACT_KIND",
            format!("unsupported artifact kind: {kind}"),
            2,
            serde_json::json!({ "kind": kind }),
        ),
        other => CliError::new("ARTIFACT_IDENTIFY_FAILED", other.to_string(), 1),
    }
}

fn run_inspect(args: InspectArgs) -> CliResult<()> {
    let bytes = read_input(&args.dump)?;
    let report = inspect_bytes(&bytes).map_err(map_inspect_error)?;
    write_json(&args.output, &report)
}

fn run_analyze(args: AnalyzeArgs) -> CliResult<()> {
    let bytes = read_input(&args.dump)?;
    let report = if let Some(path) = &args.inspect {
        let inspect_bytes = read_input(path)?;
        serde_json::from_slice::<InspectReport>(&inspect_bytes)
            .map_err(|error| CliError::invalid_inspect(path, error))?
    } else {
        inspect_bytes(&bytes).map_err(map_inspect_error)?
    };

    if let Some(profile) = &args.capture_profile {
        if !["light-crash", "rich-crash", "hang", "full-memory"].contains(&profile.as_str()) {
            return Err(CliError::new(
                "INVALID_ARGUMENT",
                format!("unsupported capture profile: {profile}"),
                2,
            ));
        }
    }
    if let Some(digest) = &args.core_image_digest {
        if !valid_digest(digest) {
            return Err(CliError::new(
                "INVALID_ARGUMENT",
                "--core-image-digest must match sha256:<64 lowercase hex chars>",
                2,
            ));
        }
    }
    let digest = sha256_hex(&bytes);
    let occurrence_id = format!("occ_{}", &digest[..16]);
    let analysis_id = format!("run_{}", &digest[16..32]);
    let match_report = if let Some(path) = &args.match_file {
        let match_bytes = read_input(path)?;
        let mut input = serde_json::from_slice::<MatchInput>(&match_bytes)
            .map_err(|error| CliError::invalid_inspect(path, error))?;
        resolve_match_paths(&mut input, path);
        Some(
            match_artifacts(&report, &input)
                .map_err(|error| CliError::new("ARTIFACT_MATCH_FAILED", error.to_string(), 1))?,
        )
    } else {
        None
    };
    let raw_match_report = match_report.clone();
    let module_paths = args
        .match_file
        .as_ref()
        .map(|path| {
            let mut input = read_input(path)
                .ok()
                .and_then(|bytes| serde_json::from_slice::<MatchInput>(&bytes).ok())
                .unwrap_or_default();
            resolve_match_paths(&mut input, path);
            crate::artifact::module_paths_for_unwind(&report, &input)
        })
        .unwrap_or_default();
    let (unwind, unwind_error) = if !report.threads.is_empty() {
        if module_paths.is_empty() {
            match unwind_bytes(&bytes, &[]) {
                Ok(value) => (Some(value), None),
                Err(error) => (None, Some(error.to_string())),
            }
        } else {
            match unwind_bytes_with_modules(&bytes, &module_paths) {
                Ok(value) => (Some(value), None),
                Err(error) => (None, Some(error.to_string())),
            }
        }
    } else {
        (None, None)
    };
    let symbolicator_report = args
        .match_file
        .as_ref()
        .map(|path| report_for_symbolicator(&report, path))
        .unwrap_or_else(|| report.clone());
    let (symbolication, symbolicator_version, symbolicator_raw) =
        if let (Some(endpoint), Some(unwind_report)) = (&args.symbolicator, unwind.as_ref()) {
            let (result, raw) = symbolicate_with_request_report(
                endpoint,
                &args.workspace_id,
                args.symbol_inventory_version,
                args.symbolicator_timeout,
                &symbolicator_report,
                &report,
                unwind_report,
            )
            .map_err(|error| CliError::new("SYMBOLICATOR_REQUEST_FAILED", error.to_string(), 1))?;
            let version = args
                .symbolicator_version
                .clone()
                .or(result.version.clone())
                .unwrap_or_else(|| "unknown".to_owned());
            (Some(result), version, Some(serde_json::to_value(raw).expect("raw serializes")))
        } else {
            (
                None,
                args.symbolicator_version.clone().unwrap_or_else(|| "unavailable".to_owned()),
                None,
            )
        };
    let result = CanonicalAnalysisResult::from_evidence(
        &report,
        &bytes,
        CanonicalInputs {
            workspace_id: args.workspace_id,
            occurrence_id,
            analysis_id,
            capture_profile: args.capture_profile,
            match_report,
            unwind: unwind.clone(),
            symbolication,
            symbolicator_version,
            core_image_digest: args.core_image_digest,
        },
    );
    let mut result = result;
    if let Some(error) = unwind_error {
        result.quality.warnings.push(crate::canonical::QualityWarning {
            code: "other".to_owned(),
            message: format!("rust-minidump unwind was incomplete: {error}"),
            module: None,
            debug_id: None,
        });
    }
    if let Some(context_path) = &args.analysis_context {
        let context_bytes = read_input(context_path)?;
        let context = serde_json::from_slice::<AnalysisContext>(&context_bytes)
            .map_err(|error| CliError::invalid_inspect(context_path, error))?;
        if let Some(raw_dir) = &args.raw_dir {
            fs::create_dir_all(raw_dir).map_err(|error| CliError::io(raw_dir, error))?;
            write_json(&raw_dir.join("legacy-canonical.json"), &result)?;
        }
        let cli_workspace_id = result.workspace_id.clone();
        context
            .validate_and_apply(
                &mut result,
                &report,
                &bytes,
                &cli_workspace_id,
                args.symbol_inventory_version,
            )
            .map_err(|error| CliError::new("INVALID_ANALYSIS_CONTEXT", error, 1))?;
        if let Err(error) = context.enrich_source_context(&mut result, context_path) {
            result.quality.warnings.push(source_context_warning(error));
        }
    }
    if let Some(raw_dir) = &args.raw_dir {
        fs::create_dir_all(raw_dir).map_err(|error| CliError::io(raw_dir, error))?;
        write_json(&raw_dir.join("inspect.json"), &report)?;
        if let Some(unwind) = unwind {
            write_json(&raw_dir.join("minidump.json"), &unwind)?;
        } else if let Some(error) = result
            .quality
            .warnings
            .iter()
            .find(|warning| warning.message.starts_with("rust-minidump unwind was incomplete"))
        {
            write_json(
                &raw_dir.join("minidump.json"),
                &serde_json::json!({"error": error.message}),
            )?;
        } else {
            write_json(&raw_dir.join("minidump.json"), &UnwindReport { threads: Vec::new() })?;
        }
        if let Some(path) = &args.match_file {
            let match_bytes = read_input(path)?;
            write_json(
                &raw_dir.join("match-input.json"),
                &serde_json::from_slice::<Value>(&match_bytes)
                    .map_err(|error| CliError::invalid_inspect(path, error))?,
            )?;
            if let Some(matched) = &raw_match_report {
                write_json(&raw_dir.join("match.json"), matched)?;
            }
        }
        if let Some(raw) = symbolicator_raw {
            write_json(&raw_dir.join("symbolicator.json"), &raw)?;
        }
    }
    write_json(&args.output, &result)
}

fn read_input(path: &Path) -> CliResult<Vec<u8>> {
    let metadata = fs::metadata(path).map_err(|error| {
        if error.kind() == io::ErrorKind::NotFound {
            CliError::input_not_found(path, error)
        } else {
            CliError::io(path, error)
        }
    })?;
    if metadata.len() > MAX_DUMP_BYTES as u64 {
        return Err(CliError::with_details(
            "INPUT_TOO_LARGE",
            format!("input exceeds the {MAX_DUMP_BYTES}-byte core limit"),
            2,
            serde_json::json!({ "path": path, "size": metadata.len(), "limit": MAX_DUMP_BYTES }),
        ));
    }
    fs::read(path).map_err(|error| {
        if error.kind() == io::ErrorKind::NotFound {
            CliError::input_not_found(path, error)
        } else {
            CliError::io(path, error)
        }
    })
}

fn resolve_match_paths(input: &mut MatchInput, match_path: &Path) {
    let base = match_path
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let mut specs = input.modules.iter_mut().chain(input.artifacts.iter_mut());
    for spec in &mut specs {
        for path in [&mut spec.pe_path, &mut spec.pdb_path, &mut spec.path] {
            if let Some(value) = path.as_mut() {
                if value.is_relative() {
                    *value = base.join(&*value);
                }
            }
        }
    }
}

/// Symbolication needs a usable local artifact path, while the dump's module
/// name is often the producer's original absolute path (for example a CI
/// `.build` directory that is deliberately absent in the worker).  Once the
/// artifact matcher has selected an exact identity, pass those verified paths
/// to Symbolicator.  The canonical result still uses the original dump module
/// names and the raw request/response remains auditable.
fn report_for_symbolicator(report: &InspectReport, match_path: &Path) -> InspectReport {
    let Ok(bytes) = read_input(match_path) else {
        return report.clone();
    };
    let Ok(mut input) = serde_json::from_slice::<MatchInput>(&bytes) else {
        return report.clone();
    };
    resolve_match_paths(&mut input, match_path);
    let mut specs = input.modules;
    specs.extend(input.artifacts);
    let mut patched = report.clone();
    for module in &mut patched.modules {
        let Some(spec) = specs.iter().find(|spec| {
            spec.code_id.as_ref().is_some_and(|id| id.eq_ignore_ascii_case(&module.code_id))
                || spec.debug_id.as_ref().is_some_and(|id| {
                    module.debug_id.as_ref().is_some_and(|actual| id.eq_ignore_ascii_case(actual))
                })
        }) else {
            continue;
        };
        if let Some(path) = spec.pe_path.clone().or_else(|| spec.path.clone()) {
            module.code_file = path.to_string_lossy().into_owned();
        }
        if let Some(path) = &spec.pdb_path {
            module.debug_file = Some(path.to_string_lossy().into_owned());
        }
    }
    patched
}

fn valid_digest(value: &str) -> bool {
    value.strip_prefix("sha256:").is_some_and(|hex| {
        hex.len() == 64
            && hex.bytes().all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    })
}

fn write_json<T: serde::Serialize>(path: &Path, value: &T) -> CliResult<()> {
    let encoded = serde_json::to_vec_pretty(value)
        .map_err(|error| CliError::new("SERIALIZATION_ERROR", error.to_string(), 1))?;
    if path == Path::new("-") {
        let mut stdout = io::stdout().lock();
        stdout
            .write_all(&encoded)
            .and_then(|_| stdout.write_all(b"\n"))
            .map_err(|error| CliError::new("IO_ERROR", error.to_string(), 1))?;
        return Ok(());
    }
    if let Some(parent) = path.parent().filter(|parent| !parent.as_os_str().is_empty()) {
        fs::create_dir_all(parent).map_err(|error| CliError::io(parent, error))?;
    }
    fs::write(path, encoded).map_err(|error| CliError::io(path, error))
}

fn map_inspect_error(error: crate::minidump::InspectFailure) -> CliError {
    match error.kind {
        InspectFailureKind::Unsupported => CliError::with_details(
            "UNSUPPORTED_DUMP",
            error.message,
            EXIT_UNSUPPORTED,
            Value::Object(Default::default()),
        ),
        InspectFailureKind::Corrupt => CliError::with_details(
            "CORRUPT_DUMP",
            error.message,
            EXIT_CORRUPT,
            Value::Object(Default::default()),
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    #[test]
    fn inspect_arguments_match_documented_shape() {
        let cli = Cli::try_parse_from([
            "dmp-core",
            "inspect",
            "--dump",
            "input.dmp",
            "--output",
            "inspect.json",
        ])
        .expect("inspect arguments parse");
        assert!(matches!(cli.command, Command::Inspect(_)));
    }

    #[test]
    fn identify_arguments_match_documented_shape() {
        let cli = Cli::try_parse_from([
            "dmp-core",
            "identify",
            "--kind",
            "pe",
            "--artifact",
            "app.exe",
            "--output",
            "identity.json",
        ])
        .expect("identify arguments parse");
        assert!(matches!(cli.command, Command::Identify(_)));
    }

    #[test]
    fn analyze_accepts_match_symbolicator_and_raw_arguments() {
        let cli = Cli::try_parse_from([
            "dmp-core",
            "analyze",
            "--dump",
            "input.dmp",
            "--inspect",
            "inspect.json",
            "--match",
            "match.json",
            "--symbolicator",
            "http://symbolicator:3021",
            "--symbol-inventory-version",
            "42",
            "--symbolicator-version",
            "26.7.2",
            "--core-image-digest",
            "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
            "--output",
            "result.json",
            "--raw-dir",
            "raw",
        ])
        .expect("analyze arguments parse");
        let Command::Analyze(args) = cli.command else {
            panic!("expected analyze");
        };
        assert_eq!(args.symbolicator.as_deref(), Some("http://symbolicator:3021"));
        assert_eq!(args.symbol_inventory_version, 42);
        assert_eq!(args.match_file.as_deref(), Some(Path::new("match.json")));
        assert_eq!(args.symbolicator_version.as_deref(), Some("26.7.2"));
        assert!(args.core_image_digest.is_some());
    }

    #[test]
    fn unsupported_and_corrupt_codes_are_design_codes() {
        assert_eq!(EXIT_UNSUPPORTED, 2);
        assert_eq!(EXIT_CORRUPT, 3);
    }

    #[test]
    fn symbolicator_report_uses_verified_local_artifact_paths() {
        let root = std::env::temp_dir()
            .join(format!("crash_cap_symbolicator_paths_{}", std::process::id()));
        let _ = fs::create_dir_all(&root);
        let match_path = root.join("match.json");
        fs::write(
            &match_path,
            r#"{"modules":[{"code_id":"ABC","pe_path":"verified-target.exe","pdb_path":"verified-target.pdb"}]}"#,
        )
        .expect("write match input");
        let report = InspectReport {
            schema_version: "0.1".to_owned(),
            dump: crate::minidump::InspectDump {
                kind: "user_minidump".to_owned(),
                size: 1,
                signature: "MDMP".to_owned(),
                number_of_streams: 1,
                flags: "0x0".to_owned(),
                timestamp: None,
            },
            process: crate::minidump::InspectProcess {
                pid: None,
                architecture: "x86_64".to_owned(),
                os: "windows".to_owned(),
                os_version: None,
                platform_id: Some(2),
                build_number: None,
                processor_count: None,
            },
            exception: None,
            crash_thread_id: None,
            threads: Vec::new(),
            modules: vec![crate::minidump::InspectModule {
                code_file: r#"C:\\build\\target.exe"#.to_owned(),
                code_id: "ABC".to_owned(),
                debug_file: Some(r#"C:\\build\\target.pdb"#.to_owned()),
                debug_id: Some("DBG".to_owned()),
                image_base: "0x1000".to_owned(),
                image_size: 0x1000,
                time_date_stamp: "0x0".to_owned(),
                checksum: "0x0".to_owned(),
            }],
            warnings: Vec::new(),
        };
        let patched = report_for_symbolicator(&report, &match_path);
        assert_eq!(
            patched.modules[0].code_file,
            root.join("verified-target.exe").to_string_lossy()
        );
        let expected_pdb = root.join("verified-target.pdb").to_string_lossy().into_owned();
        assert_eq!(patched.modules[0].debug_file.as_deref(), Some(expected_pdb.as_str()));
        let _ = fs::remove_dir_all(root);
    }
}
