//! Opt-in process boundary for immutable Run execution. The execution descriptor
//! is generated by the trusted Worker/deployment owner, never by a DMP producer.
//! Output directories are exclusive to one invocation, including failed attempts.

use crate::canonical::sha256_hex;
use crate::canonical_v11::{self, ObjectRef};
use crate::error::{CliError, CliResult};
use crate::frozen_context::{self, EnginePins, RunAssignment, StagedPair};
use crate::frozen_symbolicator::{self, Collected};
use clap::Args;
use serde::Deserialize;
use serde_json::{json, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File, OpenOptions};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};

#[derive(Debug, Args)]
pub struct AnalyzeFrozenArgs {
    /// Required opt-in while the frozen writer is under qualification.
    #[arg(long)]
    pub enable_frozen_v11: bool,
    /// Permit the all-zero Core image digest only for local qualification.
    #[arg(long)]
    pub allow_local_core_sentinel: bool,
    #[arg(long)]
    pub dump: PathBuf,
    #[arg(long)]
    pub inspect: PathBuf,
    #[arg(long)]
    pub run: PathBuf,
    #[arg(long)]
    pub resolution_manifest: PathBuf,
    /// Worker-owned frozen-execution-v1: independent assignment, pins and pair paths.
    #[arg(long)]
    pub execution: PathBuf,
    /// Direct pinned Symbolicator endpoint (not the legacy gateway).
    #[arg(long)]
    pub symbolicator: String,
    /// Deployment-owned content-addressed pair service root.
    #[arg(long)]
    pub pair_source_root: String,
    /// Total seconds across all sequential source partitions.
    #[arg(long, default_value_t = 90, value_parser = clap::value_parser!(u64).range(1..=300))]
    pub symbolicator_timeout: u64,
    /// New directory; an existing directory is always rejected.
    #[arg(long)]
    pub output_dir: PathBuf,
    /// Run/attempt-specific object-store prefix for the raw/ files to be stored unchanged.
    #[arg(long)]
    pub raw_object_prefix: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Execution {
    schema_version: String,
    assignment: RunAssignment,
    engines: EnginePins,
    pairs: BTreeMap<String, StagedPair>,
    #[serde(default)]
    sources: BTreeMap<String, PathBuf>,
}

fn evidence(error: impl std::fmt::Display) -> CliError {
    CliError::new("INVALID_FROZEN_EVIDENCE", error.to_string(), 1)
}

fn require(condition: bool, message: &str) -> CliResult<()> {
    if condition {
        Ok(())
    } else {
        Err(evidence(message))
    }
}

fn read_bounded(path: &Path, limit: u64) -> CliResult<Vec<u8>> {
    let file = File::open(path).map_err(|e| CliError::io(path, e))?;
    let metadata = file.metadata().map_err(|e| CliError::io(path, e))?;
    require(metadata.is_file() && metadata.len() <= limit, "input is not a bounded regular file")?;
    let mut bytes = Vec::new();
    file.take(limit + 1).read_to_end(&mut bytes).map_err(|e| CliError::io(path, e))?;
    require(bytes.len() as u64 <= limit, "input grew beyond its byte limit")?;
    Ok(bytes)
}

fn write_new(path: &Path, bytes: &[u8]) -> CliResult<()> {
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|e| CliError::io(path, e))?;
    file.write_all(bytes).and_then(|_| file.sync_all()).map_err(|e| CliError::io(path, e))
}

fn save_raw(args: &AnalyzeFrozenArgs, name: &str, bytes: &[u8]) -> CliResult<ObjectRef> {
    write_new(&args.output_dir.join("raw").join(name), bytes)?;
    Ok(ObjectRef {
        object_key: format!("{}/raw/{name}", args.raw_object_prefix),
        sha256: sha256_hex(bytes),
    })
}

fn save_json(
    args: &AnalyzeFrozenArgs,
    name: &str,
    value: &impl serde::Serialize,
) -> CliResult<ObjectRef> {
    save_raw(args, name, &serde_json::to_vec_pretty(value).map_err(evidence)?)
}

fn copy_bounded(source: &Path, destination: &Path, limit: u64) -> CliResult<()> {
    let input = File::open(source).map_err(|e| CliError::io(source, e))?;
    let metadata = input.metadata().map_err(|e| CliError::io(source, e))?;
    require(
        metadata.is_file() && metadata.len() <= limit,
        "pair input exceeds its regular-file limit",
    )?;
    let mut output = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(destination)
        .map_err(|e| CliError::io(destination, e))?;
    let copied = std::io::copy(&mut input.take(limit + 1), &mut output)
        .map_err(|e| CliError::io(destination, e))?;
    require(copied <= limit, "pair input grew beyond its byte limit")?;
    output.sync_all().map_err(|e| CliError::io(destination, e))
}

pub fn run(args: AnalyzeFrozenArgs) -> CliResult<()> {
    if !args.enable_frozen_v11 {
        return Err(CliError::new(
            "FROZEN_WRITER_DISABLED",
            "analyze-frozen requires --enable-frozen-v11",
            2,
        ));
    }
    require(
        !args.raw_object_prefix.is_empty()
            && args.raw_object_prefix.len() <= 900
            && args.raw_object_prefix.split('/').all(|segment| {
                !segment.is_empty()
                    && segment != "."
                    && segment != ".."
                    && segment.bytes().all(|b| b.is_ascii_alphanumeric() || b"-_.".contains(&b))
            }),
        "raw object prefix must contain safe nonempty relative key segments",
    )?;
    let limit = frozen_context::MAX_INPUT_BYTES as u64;
    let execution_bytes = read_bounded(&args.execution, limit)?;
    let mut execution: Execution =
        serde_json::from_value(frozen_context::strict_json(&execution_bytes).map_err(evidence)?)
            .map_err(evidence)?;
    require(execution.schema_version == "frozen-execution-v1", "unsupported execution descriptor")?;
    require(
        args.allow_local_core_sentinel
            || execution.engines.core_image_digest != format!("sha256:{}", "0".repeat(64)),
        "local Core image sentinel requires --allow-local-core-sentinel",
    )?;
    let run_bytes = read_bounded(&args.run, limit)?;
    let manifest_bytes = read_bounded(&args.resolution_manifest, limit)?;
    let inspect_bytes = read_bounded(&args.inspect, limit)?;
    let dump = read_bounded(&args.dump, crate::minidump::MAX_DUMP_BYTES as u64)?;
    let verified = frozen_context::verify(
        &run_bytes,
        &manifest_bytes,
        &inspect_bytes,
        &dump,
        &execution.engines,
        &execution.assignment,
    )
    .map_err(evidence)?;
    let source_ids = verified.run()["source_bundle_locations"]
        .as_array()
        .unwrap()
        .iter()
        .map(|source| source["artifact_id"].as_str().unwrap())
        .collect::<BTreeSet<_>>();
    require(
        execution.sources.keys().all(|id| source_ids.contains(id.as_str())),
        "execution source set contains an unfrozen artifact",
    )?;
    let selected = verified
        .selections()
        .iter()
        .filter_map(|s| s.selected_pair_id.clone())
        .collect::<BTreeSet<_>>();
    require(
        execution.pairs.keys().cloned().collect::<BTreeSet<_>>() == selected,
        "execution pair set differs from the frozen selection",
    )?;
    let base = args.execution.parent().unwrap_or(Path::new("."));
    for pair in execution.pairs.values_mut() {
        for path in [&mut pair.pe, &mut pair.pdb] {
            if path.is_relative() {
                *path = base.join(&*path);
            }
        }
    }
    for path in execution.sources.values_mut() {
        if path.is_relative() {
            *path = base.join(&*path);
        }
    }
    // Validate deployment URLs even when this Run has no symbol partitions.
    frozen_symbolicator::pair_source(&"0".repeat(64), &args.pair_source_root).map_err(evidence)?;
    frozen_symbolicator::pair_source(&"0".repeat(64), &args.symbolicator).map_err(evidence)?;
    fs::create_dir(&args.output_dir).map_err(|e| CliError::io(&args.output_dir, e))?;
    let result = (|| {
        for directory in ["raw", "staged"] {
            let path = args.output_dir.join(directory);
            fs::create_dir(&path).map_err(|e| CliError::io(&path, e))?;
        }
        save_raw(&args, "run.json", &run_bytes)?;
        save_raw(&args, "resolution-manifest.json", &manifest_bytes)?;
        save_raw(&args, "inspect.json", &inspect_bytes)?;
        save_raw(&args, "execution.json", &execution_bytes)?;
        let mut pairs = BTreeMap::new();
        for (key, pair) in &execution.pairs {
            let pe = args.output_dir.join("staged").join(format!("{key}.pe"));
            let pdb = args.output_dir.join("staged").join(format!("{key}.pdb"));
            copy_bounded(&pair.pe, &pe, crashcap_artifact_identity::MAX_PE_BYTES)?;
            copy_bounded(&pair.pdb, &pdb, crashcap_artifact_identity::MAX_PDB_BYTES)?;
            pairs.insert(key.clone(), StagedPair { pe, pdb });
        }
        let paths = verified.verify_pairs(&pairs).map_err(evidence)?;
        let deadline = Instant::now() + Duration::from_secs(args.symbolicator_timeout);
        let public = crate::frozen_public_pe::unwind(
            crate::frozen_public_pe::PublicPeRequest {
                dump: &dump,
                inspect: verified.inspect(),
                selections: verified.selections(),
                sources: verified.public_sources(),
                engine: &args.symbolicator,
                raw_dir: &args.output_dir.join("raw"),
                raw_prefix: &args.raw_object_prefix,
                deadline: Instant::now()
                    + Duration::from_secs((args.symbolicator_timeout / 2).min(30)),
            },
            paths,
        )
        .map_err(evidence)?;
        let unwind = public.report;
        save_json(&args, "minidump.json", &unwind)?;
        let plan = frozen_symbolicator::plan(
            verified.inspect(),
            &unwind,
            verified.selections(),
            &args.pair_source_root,
            verified.public_sources(),
        )
        .map_err(evidence)?;
        save_json(&args, "source-plan.json", &plan)?;
        let mut collected = Collected { frames: vec![], modules: vec![] };
        for (index, partition) in plan.partitions.iter().enumerate() {
            let remaining = deadline.saturating_duration_since(Instant::now());
            require(!remaining.is_zero(), "total source request budget exhausted")?;
            let transport = frozen_symbolicator::execute(
                &args.symbolicator,
                partition,
                remaining.as_secs() + u64::from(remaining.subsec_nanos() != 0),
            )
            .map_err(evidence)?;
            let diagnostic =
                save_json(&args, &format!("source-{index}-transport.json"), &transport)?;
            if let Some(failure) = &transport.failure {
                return Err(CliError::with_details(
                    "FROZEN_SOURCE_FAILED",
                    failure,
                    1,
                    json!({"partition_index":index,"diagnostic_ref":diagnostic}),
                ));
            }
            let result = frozen_symbolicator::collect(
                partition,
                transport.response.as_ref().ok_or_else(|| evidence("source response missing"))?,
                diagnostic,
            )
            .map_err(evidence)?;
            collected.frames.extend(result.frames);
            collected.modules.extend(result.modules);
        }
        let mut outcomes = BTreeMap::new();
        for (index, outcome) in collected.modules {
            require(
                outcomes.insert(index, outcome).is_none(),
                "module appeared in multiple source partitions",
            )?;
        }
        for (index, public_outcomes) in public.outcomes {
            outcomes.entry(index).or_insert_with(Vec::new).extend(public_outcomes);
        }
        let mut canonical = canonical_v11::assemble(
            &inspect_bytes,
            &dump,
            &unwind,
            &collected.frames,
            verified.canonical_inputs(outcomes).map_err(evidence)?,
        )
        .map_err(evidence)?;
        let source_diagnostic =
            crate::frozen_source::enrich(verified.run(), &execution.sources, &mut canonical);
        save_json(&args, "source-bundles.json", &source_diagnostic)?;
        let value = serde_json::to_value(&canonical).map_err(evidence)?;
        let schema: Value =
            serde_json::from_str(include_str!("../../contracts/analysis-result-v1.1.schema.json"))
                .map_err(evidence)?;
        let validator = jsonschema::validator_for(&schema).map_err(evidence)?;
        require(
            validator.is_valid(&value),
            "native Canonical does not satisfy the 1.1 output contract",
        )?;
        write_new(
            &args.output_dir.join("canonical.json"),
            &serde_json::to_vec_pretty(&value).map_err(evidence)?,
        )
    })();
    if let Err(error) = &result {
        // Diagnostic failure must not replace the original execution error.
        let _ = write_new(&args.output_dir.join("failure.json"), error.to_json_line().as_bytes());
    }
    result
}
