"""Upload v3 empty-database baseline. Restore the old stack and backup to roll back."""
from alembic import op

revision = "0001_upload_v3"
down_revision = None
branch_labels = None
depends_on = None

STATEMENTS = [
    'CREATE TABLE catalog_watermark (\n\tid INTEGER NOT NULL, \n\trevision BIGINT NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_catalog_watermark CHECK (id = 1 AND revision >= 0)\n)',
    "CREATE TABLE catalog_files (\n\tid CHAR(64) NOT NULL, \n\tkind TEXT NOT NULL, \n\traw_sha256 CHAR(64) NOT NULL, \n\traw_size BIGINT NOT NULL, \n\tcode_id TEXT, \n\tdebug_id TEXT, \n\tarchitecture TEXT NOT NULL, \n\tvalidator_version TEXT NOT NULL, \n\tverification_object_key TEXT NOT NULL, \n\tverification_sha256 CHAR(64) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_catalog_files_content UNIQUE (kind, raw_sha256), \n\tCONSTRAINT ck_catalog_files_shape CHECK (kind IN ('pe','pdb') AND raw_size > 0), \n\tCONSTRAINT ck_catalog_files_arch CHECK (architecture IN ('x86_64','unknown')), \n\tCONSTRAINT ck_catalog_files_pe_identity CHECK (kind <> 'pe' OR code_id IS NOT NULL)\n)",
    'CREATE TABLE workspaces (\n\tid TEXT NOT NULL, \n\tname TEXT NOT NULL, \n\tdisplay_name TEXT, \n\tplatform TEXT DEFAULT \'windows\' NOT NULL, \n\tdefault_architecture TEXT DEFAULT \'x86_64\' NOT NULL, \n\tretention_days INTEGER DEFAULT 180 NOT NULL, \n\tsymbol_inventory_version BIGINT DEFAULT 0 NOT NULL, \n\tin_app_rules JSONB DEFAULT \'{"include_modules":[],"exclude_modules":[]}\' NOT NULL, \n\tin_app_rule_version BIGINT DEFAULT 0 NOT NULL, \n\tmodule_role_version BIGINT DEFAULT 0 NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_workspaces_name UNIQUE (name), \n\tCONSTRAINT ck_workspaces_platform CHECK (platform = \'windows\'), \n\tCONSTRAINT ck_workspaces_architecture CHECK (default_architecture = \'x86_64\'), \n\tCONSTRAINT ck_workspaces_retention_days CHECK (retention_days > 0), \n\tCONSTRAINT ck_workspaces_symbol_inventory CHECK (symbol_inventory_version >= 0), \n\tCONSTRAINT ck_workspaces_in_app_rule_version CHECK (in_app_rule_version >= 0), \n\tCONSTRAINT ck_workspaces_module_role_version CHECK (module_role_version >= 0)\n)',
    'CREATE TABLE analysis_event_cursors (\n\tid TEXT NOT NULL, \n\trevision BIGINT NOT NULL, \n\tafter_occurrence_id TEXT, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_analysis_event_cursors_revision CHECK (revision >= 0)\n)',
    'CREATE TABLE analysis_scheduler_state (\n\tid INTEGER NOT NULL, \n\tlast_workspace_id TEXT, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_analysis_scheduler_state_singleton CHECK (id = 1)\n)',
    "CREATE TABLE task_intents (\n\tattempt_id TEXT NOT NULL, \n\tschema_version TEXT DEFAULT '1.0' NOT NULL, \n\ttask_type TEXT NOT NULL, \n\tqueue TEXT NOT NULL, \n\tlogical_key TEXT NOT NULL, \n\ttarget_type TEXT NOT NULL, \n\ttarget_id TEXT NOT NULL, \n\tmessage JSONB NOT NULL, \n\trequest_id TEXT, \n\tstate TEXT DEFAULT 'pending' NOT NULL, \n\tdue_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\trelay_owner TEXT, \n\trelay_generation BIGINT DEFAULT 0 NOT NULL, \n\trelay_lease_until TIMESTAMP WITH TIME ZONE, \n\tdelivery_attempts INTEGER DEFAULT 0 NOT NULL, \n\tpublished_at TIMESTAMP WITH TIME ZONE, \n\tdead_at TIMESTAMP WITH TIME ZONE, \n\tlast_error_code TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (attempt_id), \n\tCONSTRAINT uq_task_intents_type_logical_key UNIQUE (task_type, logical_key), \n\tCONSTRAINT ck_task_intents_schema_version CHECK (schema_version IN ('1.0', '1.2')), \n\tCONSTRAINT ck_task_intents_type CHECK (task_type IN ('verify_upload', 'dispatch_workspace_role', 'analyze_frozen_run')), \n\tCONSTRAINT ck_task_intents_queue CHECK (queue IN ('verify', 'ingest', 'dump-small', 'dump-large')), \n\tCONSTRAINT ck_task_intents_state CHECK (state IN ('pending', 'publishing', 'published', 'dead')), \n\tCONSTRAINT ck_task_intents_relay_generation CHECK (relay_generation >= 0), \n\tCONSTRAINT ck_task_intents_delivery_attempts CHECK (delivery_attempts >= 0)\n)",
    'CREATE INDEX ix_task_intents_target ON task_intents (task_type, target_type, target_id)',
    'CREATE INDEX ix_task_intents_due ON task_intents (state, due_at)',
    'CREATE INDEX ix_task_intents_relay_lease ON task_intents (state, relay_lease_until)',
    "CREATE TABLE catalog_file_locations (\n\tid CHAR(64) NOT NULL, \n\tfile_id CHAR(64) NOT NULL, \n\tobject_key TEXT NOT NULL, \n\tpayload_encoding TEXT NOT NULL, \n\tpayload_sha256 CHAR(64) NOT NULL, \n\tpayload_size BIGINT NOT NULL, \n\tretention_basis TEXT NOT NULL, \n\tstate TEXT NOT NULL, \n\tverification_object_key TEXT NOT NULL, \n\tverification_sha256 CHAR(64) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_catalog_locations_object UNIQUE (object_key), \n\tCONSTRAINT ck_catalog_locations_payload CHECK (payload_encoding IN ('identity','zstd-v1') AND payload_size > 0), \n\tCONSTRAINT ck_catalog_locations_state CHECK (state IN ('available','unavailable')), \n\tCONSTRAINT ck_catalog_locations_retention CHECK (retention_basis = 'platform_owned'), \n\tFOREIGN KEY(file_id) REFERENCES catalog_files (id)\n)",
    'CREATE INDEX ix_catalog_locations_file ON catalog_file_locations (file_id, state)',
    "CREATE TABLE catalog_pairs (\n\tid CHAR(64) NOT NULL, \n\tpe_file_id CHAR(64) NOT NULL, \n\tpdb_file_id CHAR(64) NOT NULL, \n\tcode_id TEXT NOT NULL, \n\tdebug_id TEXT NOT NULL, \n\tarchitecture TEXT NOT NULL, \n\tstate TEXT NOT NULL, \n\tqualification_version BIGINT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_catalog_pairs_content UNIQUE (pe_file_id, pdb_file_id), \n\tCONSTRAINT ck_catalog_pairs_qualification CHECK (state IN ('active','withdrawn') AND qualification_version > 0), \n\tCONSTRAINT ck_catalog_pairs_arch CHECK (architecture = 'x86_64'), \n\tFOREIGN KEY(pe_file_id) REFERENCES catalog_files (id), \n\tFOREIGN KEY(pdb_file_id) REFERENCES catalog_files (id)\n)",
    "CREATE TABLE workspace_module_roles (\n\tworkspace_id TEXT NOT NULL, \n\tversion BIGINT NOT NULL, \n\tcode_id TEXT NOT NULL, \n\tdebug_id TEXT NOT NULL, \n\tarchitecture TEXT NOT NULL, \n\trole TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (workspace_id, version), \n\tCONSTRAINT ck_workspace_module_roles_version CHECK (version > 0), \n\tCONSTRAINT ck_workspace_module_roles_architecture CHECK (architecture = 'x86_64'), \n\tCONSTRAINT ck_workspace_module_roles_role CHECK (role IN ('owned','dependency')), \n\tCONSTRAINT ck_workspace_module_roles_code_id CHECK (code_id ~ '^[0-9a-f]{9,24}$'), \n\tCONSTRAINT ck_workspace_module_roles_debug_id CHECK (debug_id ~ '^[0-9a-f]{33,40}$'), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id)\n)",
    'CREATE INDEX ix_workspace_module_roles_identity_version ON workspace_module_roles (workspace_id, code_id, debug_id, architecture, version DESC)',
    "CREATE TABLE dump_blobs (\n\tid TEXT NOT NULL, \n\tworkspace_id TEXT NOT NULL, \n\tsha256 CHAR(64) NOT NULL, \n\tsize BIGINT NOT NULL, \n\tobject_key TEXT NOT NULL, \n\tdump_kind TEXT DEFAULT 'user_minidump' NOT NULL, \n\tarchitecture TEXT, \n\tcapture_profile TEXT, \n\tverification_status TEXT DEFAULT 'VERIFYING' NOT NULL, \n\tuploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_dump_blobs_workspace_sha256 UNIQUE (workspace_id, sha256), \n\tCONSTRAINT ck_dump_blobs_size CHECK (size >= 0), \n\tCONSTRAINT ck_dump_blobs_capture_profile CHECK (capture_profile IS NULL OR capture_profile IN ('light-crash','rich-crash','hang','full-memory')), \n\tCONSTRAINT ck_dump_blobs_kind CHECK (dump_kind = 'user_minidump'), \n\tCONSTRAINT ck_dump_blobs_verification_status CHECK (verification_status IN ('INITIALIZED', 'UPLOADING', 'UPLOADED', 'VERIFYING', 'ACCEPTED', 'QUARANTINED', 'REJECTED')), \n\tCONSTRAINT ck_dump_blobs_sha256 CHECK (sha256 ~ '^[0-9a-fA-F]{64}$'), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id)\n)",
    "CREATE TABLE missing_symbols (\n\tid TEXT NOT NULL, \n\tworkspace_id TEXT NOT NULL, \n\tidentity_key TEXT NOT NULL, \n\tcode_file TEXT, \n\tcode_id TEXT NOT NULL, \n\tdebug_file TEXT, \n\tdebug_id TEXT NOT NULL, \n\tfirst_seen TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tlast_seen TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\taffected_occurrence_count INTEGER DEFAULT 0 NOT NULL, \n\tstatus TEXT DEFAULT 'open' NOT NULL, \n\tPRIMARY KEY (id, code_id, debug_id), \n\tCONSTRAINT ck_missing_symbols_status CHECK (status IN ('open', 'resolved', 'ignored')), \n\tCONSTRAINT ck_missing_symbols_affected_count CHECK (affected_occurrence_count >= 0), \n\tCONSTRAINT uq_missing_symbols_id UNIQUE (id), \n\tCONSTRAINT uq_missing_symbols_workspace_identity UNIQUE (workspace_id, identity_key), \n\tCONSTRAINT uq_missing_symbols_id_workspace UNIQUE (id, workspace_id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id)\n)",
    "CREATE TABLE task_executions (\n\ttask_type TEXT NOT NULL, \n\tlogical_key TEXT NOT NULL, \n\tactive_attempt_id TEXT NOT NULL, \n\tgeneration BIGINT DEFAULT 0 NOT NULL, \n\towner_id TEXT, \n\tlease_until TIMESTAMP WITH TIME ZONE, \n\toutcome TEXT DEFAULT 'idle' NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (task_type, logical_key), \n\tCONSTRAINT ck_task_executions_type CHECK (task_type IN ('verify_upload', 'dispatch_workspace_role', 'analyze_frozen_run')), \n\tCONSTRAINT ck_task_executions_generation CHECK (generation >= 0), \n\tCONSTRAINT ck_task_executions_outcome CHECK (outcome IN ('idle', 'running', 'succeeded', 'failed', 'dead')), \n\tFOREIGN KEY(active_attempt_id) REFERENCES task_intents (attempt_id)\n)",
    'CREATE INDEX ix_task_executions_lease ON task_executions (outcome, lease_until)',
    "CREATE TABLE uploads (\n\tid TEXT NOT NULL, \n\tworkspace_id TEXT, \n\tobject_key TEXT NOT NULL, \n\toriginal_filename TEXT NOT NULL, \n\tdeclared_length BIGINT NOT NULL, \n\tverified_length BIGINT, \n\tclient_sha256_hint CHAR(64), \n\tverified_sha256 CHAR(64), \n\twire_encoding TEXT DEFAULT 'identity' NOT NULL, \n\twire_declared_length BIGINT NOT NULL, \n\twire_sha256_hint CHAR(64), \n\tverified_wire_length BIGINT, \n\tverified_wire_sha256 CHAR(64), \n\trejection_reason TEXT, \n\tuploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tsource_ip TEXT, \n\tfile_kind TEXT NOT NULL, \n\tversion TEXT, \n\tsource TEXT DEFAULT 'api' NOT NULL, \n\tverification_status TEXT DEFAULT 'INITIALIZED' NOT NULL, \n\tcapture_profile TEXT, \n\treported_at TIMESTAMP WITH TIME ZONE, \n\texpires_at TIMESTAMP WITH TIME ZONE, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tpayload_deleted_at TIMESTAMP WITH TIME ZONE, \n\tpayload_deletion_reason TEXT, \n\tpayload_deletion_attempts INTEGER DEFAULT 0 NOT NULL, \n\tpayload_delete_claim_token TEXT, \n\tpayload_delete_lease_expires_at TIMESTAMP WITH TIME ZONE, \n\tpayload_delete_last_error TEXT, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_uploads_object_key UNIQUE (object_key), \n\tCONSTRAINT ck_uploads_declared_length CHECK (declared_length >= 0), \n\tCONSTRAINT ck_uploads_verified_length CHECK (verified_length IS NULL OR verified_length >= 0), \n\tCONSTRAINT ck_uploads_wire_encoding CHECK (wire_encoding IN ('identity', 'zstd-v1')), \n\tCONSTRAINT ck_uploads_wire_declared_length CHECK (wire_declared_length > 0), \n\tCONSTRAINT ck_uploads_verified_wire_length CHECK (verified_wire_length IS NULL OR verified_wire_length >= 0), \n\tCONSTRAINT ck_uploads_wire_sha256_hint CHECK (wire_sha256_hint IS NULL OR wire_sha256_hint ~ '^[0-9a-f]{64}$'), \n\tCONSTRAINT ck_uploads_verified_wire_sha256 CHECK (verified_wire_sha256 IS NULL OR verified_wire_sha256 ~ '^[0-9a-f]{64}$'), \n\tCONSTRAINT ck_uploads_file_kind CHECK (file_kind IN ('dmp', 'pe', 'pdb')), \n\tCONSTRAINT ck_uploads_verification_status CHECK (verification_status IN ('INITIALIZED', 'UPLOADING', 'UPLOADED', 'VERIFYING', 'ACCEPTED', 'QUARANTINED', 'REJECTED')), \n\tCONSTRAINT ck_uploads_client_sha256_hint CHECK (client_sha256_hint IS NULL OR client_sha256_hint ~ '^[0-9a-fA-F]{64}$'), \n\tCONSTRAINT ck_uploads_verified_sha256 CHECK (verified_sha256 IS NULL OR verified_sha256 ~ '^[0-9a-fA-F]{64}$'), \n\tCONSTRAINT ck_uploads_payload_deletion_attempts CHECK (payload_deletion_attempts >= 0), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id)\n)",
    'CREATE INDEX ix_uploads_workspace_dmp_status_uploaded ON uploads (workspace_id, file_kind, verification_status, uploaded_at DESC)',
    'CREATE INDEX ix_uploads_payload_gc_eligibility ON uploads (verification_status, payload_deleted_at, completed_at)',
    'CREATE INDEX ix_uploads_payload_gc_lease ON uploads (payload_delete_lease_expires_at, id)',
    "CREATE TABLE operation_logs (\n\tid BIGSERIAL NOT NULL, \n\tworkspace_id TEXT, \n\tactor TEXT DEFAULT 'anonymous' NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\trequest_id TEXT, \n\tsource_ip TEXT, \n\tuser_agent TEXT, \n\taction TEXT NOT NULL, \n\ttarget_type TEXT, \n\ttarget_id TEXT, \n\tresult TEXT, \n\tdetails JSONB, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_operation_logs_actor CHECK (actor = 'anonymous'), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id)\n)",
    "CREATE TABLE catalog_pair_origins (\n\tid TEXT NOT NULL, \n\tpair_id CHAR(64) NOT NULL, \n\torigin_type TEXT NOT NULL, \n\torigin_key TEXT NOT NULL, \n\tsource_workspace_id TEXT, \n\tdetails JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_catalog_origins_source_pair UNIQUE (origin_type, origin_key, pair_id), \n\tCONSTRAINT ck_catalog_origins_type CHECK (origin_type = 'upload'), \n\tFOREIGN KEY(pair_id) REFERENCES catalog_pairs (id), \n\tFOREIGN KEY(source_workspace_id) REFERENCES workspaces (id)\n)",
    'CREATE TABLE catalog_identity_memberships (\n\tpair_id CHAR(64) NOT NULL, \n\tcode_id TEXT NOT NULL, \n\tdebug_id TEXT NOT NULL, \n\tarchitecture TEXT NOT NULL, \n\tPRIMARY KEY (pair_id), \n\tFOREIGN KEY(pair_id) REFERENCES catalog_pairs (id)\n)',
    'CREATE INDEX ix_catalog_memberships_code ON catalog_identity_memberships (code_id, architecture)',
    'CREATE INDEX ix_catalog_memberships_debug ON catalog_identity_memberships (debug_id, architecture)',
    "CREATE TABLE catalog_pair_reviews (\n\tid TEXT NOT NULL, \n\tpair_id CHAR(64) NOT NULL, \n\tqualification_version BIGINT NOT NULL, \n\tstate TEXT NOT NULL, \n\tidempotency_key TEXT NOT NULL, \n\trequest_sha256 CHAR(64) NOT NULL, \n\treason TEXT NOT NULL, \n\tevidence_object_key TEXT NOT NULL, \n\tevidence_sha256 CHAR(64) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_catalog_reviews_version UNIQUE (pair_id, qualification_version), \n\tCONSTRAINT uq_catalog_reviews_idempotency UNIQUE (idempotency_key), \n\tCONSTRAINT ck_catalog_reviews_state CHECK (state IN ('active','withdrawn') AND qualification_version > 1), \n\tFOREIGN KEY(pair_id) REFERENCES catalog_pairs (id)\n)",
    'CREATE TABLE dump_inspections (\n\tid CHAR(64) NOT NULL, \n\tdump_blob_id TEXT NOT NULL, \n\tinspector_version TEXT NOT NULL, \n\tinspector_provenance TEXT NOT NULL, \n\tdump_sha256 CHAR(64) NOT NULL, \n\tdump_size BIGINT NOT NULL, \n\tobject_key TEXT NOT NULL, \n\tobject_sha256 CHAR(64) NOT NULL, \n\tmodules JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_dump_inspections_version UNIQUE (dump_blob_id, inspector_version, inspector_provenance), \n\tCONSTRAINT ck_dump_inspections_size CHECK (dump_size > 0), \n\tFOREIGN KEY(dump_blob_id) REFERENCES dump_blobs (id)\n)',
    "CREATE TABLE occurrences (\n\tid TEXT NOT NULL, \n\tworkspace_id TEXT NOT NULL, \n\tdump_blob_id TEXT NOT NULL, \n\tversion TEXT, \n\tcurrent_run_id TEXT, \n\tdump_timestamp TIMESTAMP WITH TIME ZONE, \n\treported_at TIMESTAMP WITH TIME ZONE, \n\tuploaded_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\ttime_source TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_occurrences_dump_blob_id UNIQUE (dump_blob_id), \n\tCONSTRAINT uq_occurrences_id_workspace UNIQUE (id, workspace_id), \n\tCONSTRAINT ck_occurrences_time_source CHECK (time_source IN ('dump', 'reported', 'uploaded', 'manual')), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id), \n\tFOREIGN KEY(dump_blob_id) REFERENCES dump_blobs (id)\n)",
    'CREATE INDEX ix_occurrences_workspace_occurred_id ON occurrences (workspace_id, occurred_at DESC, id DESC)',
    "CREATE TABLE artifact_entries (\n\tid TEXT NOT NULL, \n\tfile_id CHAR(64), \n\tworkspace_id TEXT, \n\tupload_id TEXT NOT NULL, \n\tname TEXT NOT NULL, \n\tversion TEXT, \n\tkind TEXT NOT NULL, \n\tsource TEXT NOT NULL, \n\tavailability TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_artifact_entries_upload UNIQUE (upload_id), \n\tCONSTRAINT ck_artifact_entries_kind CHECK (kind IN ('pe','pdb')), \n\tCONSTRAINT ck_artifact_entries_source CHECK (source IN ('api','cli','browser')), \n\tCONSTRAINT ck_artifact_entries_availability CHECK (availability IN ('validating','waiting_for_pair','symbols_available','identity_conflict','no_debug_identity','storage_unavailable')), \n\tFOREIGN KEY(file_id) REFERENCES catalog_files (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id), \n\tFOREIGN KEY(upload_id) REFERENCES uploads (id)\n)",
    'CREATE INDEX ix_artifact_entries_scope_created ON artifact_entries (workspace_id, created_at DESC)',
    'CREATE INDEX ix_artifact_entries_file_scope ON artifact_entries (file_id, workspace_id)',
    'CREATE TABLE catalog_changes (\n\trevision BIGINT NOT NULL, \n\tpair_id CHAR(64), \n\tfile_id CHAR(64), \n\tcode_id TEXT, \n\tdebug_id TEXT, \n\tarchitecture TEXT NOT NULL, \n\tchange_type TEXT NOT NULL, \n\taffects_selection BOOLEAN NOT NULL, \n\treview_id TEXT, \n\tdetails JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (revision), \n\tCONSTRAINT ck_catalog_changes_revision CHECK (revision > 0), \n\tFOREIGN KEY(pair_id) REFERENCES catalog_pairs (id), \n\tFOREIGN KEY(file_id) REFERENCES catalog_files (id), \n\tFOREIGN KEY(review_id) REFERENCES catalog_pair_reviews (id)\n)',
    "CREATE TABLE auto_analysis_demands (\n\tid TEXT NOT NULL, \n\toccurrence_id TEXT NOT NULL, \n\tworkspace_id TEXT NOT NULL, \n\tinspection_id CHAR(64), \n\tstate TEXT NOT NULL, \n\treason TEXT NOT NULL, \n\tgeneration BIGINT NOT NULL, \n\tretry_attempt INTEGER NOT NULL, \n\tchange_sequence BIGINT NOT NULL, \n\tplanned_sequence BIGINT NOT NULL, \n\tindex_revision BIGINT NOT NULL, \n\tfirst_event_at TIMESTAMP WITH TIME ZONE, \n\tlast_event_at TIMESTAMP WITH TIME ZONE, \n\tnot_before TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_analysis_demands_occurrence UNIQUE (occurrence_id), \n\tFOREIGN KEY(occurrence_id, workspace_id) REFERENCES occurrences (id, workspace_id), \n\tCONSTRAINT ck_analysis_demands_counters CHECK (generation >= 0 AND retry_attempt >= 0), \n\tCONSTRAINT ck_analysis_demands_sequence CHECK (planned_sequence >= 0 AND change_sequence >= planned_sequence), \n\tCONSTRAINT ck_analysis_demands_revision CHECK (index_revision >= 0), \n\tCONSTRAINT ck_analysis_demands_state CHECK (state IN ('preparing','coalescing','queued','running','updated','retained','needs_review','retry_wait','retry_exhausted','cannot_recompute','paused')), \n\tFOREIGN KEY(inspection_id) REFERENCES dump_inspections (id)\n)",
    'CREATE INDEX ix_analysis_demands_ready ON auto_analysis_demands (state, not_before, workspace_id, id)',
    'CREATE TABLE dump_symbol_references (\n\toccurrence_id TEXT NOT NULL, \n\tmodule_index INTEGER NOT NULL, \n\tinspection_id CHAR(64) NOT NULL, \n\tcode_id TEXT, \n\tdebug_id TEXT, \n\tarchitecture TEXT NOT NULL, \n\tPRIMARY KEY (occurrence_id, module_index), \n\tCONSTRAINT ck_dump_symbol_references_index CHECK (module_index >= 0), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id), \n\tFOREIGN KEY(inspection_id) REFERENCES dump_inspections (id)\n)',
    'CREATE INDEX ix_dump_symbol_references_code ON dump_symbol_references (code_id, occurrence_id)',
    'CREATE INDEX ix_dump_symbol_references_debug ON dump_symbol_references (debug_id, occurrence_id)',
    'CREATE TABLE occurrence_submissions (\n\tupload_id TEXT NOT NULL, \n\toccurrence_id TEXT, \n\tlabel TEXT, \n\tbatch TEXT, \n\tsource TEXT NOT NULL, \n\tfilename TEXT NOT NULL, \n\tversion TEXT, \n\tsubmitted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tverified_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (upload_id), \n\tCONSTRAINT ck_occurrence_submissions_verified CHECK ((occurrence_id IS NULL AND verified_at IS NULL) OR (occurrence_id IS NOT NULL AND verified_at IS NOT NULL)), \n\tFOREIGN KEY(upload_id) REFERENCES uploads (id), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id)\n)',
    'CREATE INDEX ix_occurrence_submissions_history ON occurrence_submissions (occurrence_id, upload_id)',
    'CREATE TABLE occurrence_version_audits (\n\tid TEXT NOT NULL, \n\toccurrence_id TEXT NOT NULL, \n\told_version TEXT, \n\tnew_version TEXT, \n\tsource TEXT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id)\n)',
    'CREATE TABLE analysis_demand_restarts (\n\tid TEXT NOT NULL, \n\tdemand_id TEXT NOT NULL, \n\tidempotency_key TEXT NOT NULL, \n\trequest_sha256 CHAR(64) NOT NULL, \n\trequest JSONB NOT NULL, \n\tresponse JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_analysis_demand_restart_request UNIQUE (demand_id, idempotency_key), \n\tFOREIGN KEY(demand_id) REFERENCES auto_analysis_demands (id)\n)',
    "CREATE TABLE analysis_demand_targets (\n\tdemand_id TEXT NOT NULL, \n\tgeneration BIGINT NOT NULL, \n\tinspection_id CHAR(64) NOT NULL, \n\tresolution_fingerprint CHAR(64) NOT NULL, \n\tcontext_sha256 CHAR(64) NOT NULL, \n\tcause TEXT NOT NULL, \n\tmanifest_object_key TEXT NOT NULL, \n\tmanifest_sha256 CHAR(64) NOT NULL, \n\tcatalog_revision BIGINT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (demand_id, generation), \n\tCONSTRAINT ck_demand_targets_cause CHECK (cause IN ('initial','symbol_refresh','role_change','engine_upgrade','evidence_correction','manual')), \n\tCONSTRAINT ck_demand_targets_counters CHECK (generation > 0 AND catalog_revision >= 0), \n\tFOREIGN KEY(demand_id) REFERENCES auto_analysis_demands (id), \n\tFOREIGN KEY(inspection_id) REFERENCES dump_inspections (id)\n)",
    "CREATE TABLE analysis_runs (\n\tid TEXT NOT NULL, \n\toccurrence_id TEXT NOT NULL, \n\tdemand_id TEXT, \n\tdemand_generation BIGINT, \n\tretry_attempt INTEGER, \n\trun_spec JSONB NOT NULL, \n\tcore_version TEXT NOT NULL, \n\tcore_image_digest TEXT NOT NULL, \n\tsymbolicator_version TEXT NOT NULL, \n\tschema_version TEXT DEFAULT '2.0' NOT NULL, \n\tgrouping_version TEXT DEFAULT 'group-v1.1' NOT NULL, \n\tnormalization_version TEXT DEFAULT 'norm-v1.0' NOT NULL, \n\tsymbol_inventory_version BIGINT NOT NULL, \n\tidempotency_key CHAR(64) NOT NULL, \n\tstatus TEXT NOT NULL, \n\tquality_score REAL, \n\tresult_object_key TEXT, \n\traw_object_prefix TEXT, \n\tinspect_object_key TEXT, \n\tanalysis_context JSONB, \n\tassembly_mode TEXT DEFAULT 'core-final' NOT NULL, \n\twinner_attempt_id TEXT, \n\twinner_generation BIGINT, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\terror_code TEXT, \n\terror_detail TEXT, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_analysis_runs_idempotency_key UNIQUE (idempotency_key), \n\tCONSTRAINT uq_analysis_runs_demand_attempt UNIQUE (demand_id, demand_generation, retry_attempt), \n\tCONSTRAINT ck_analysis_runs_demand_attempt CHECK ((demand_id IS NULL AND demand_generation IS NULL AND retry_attempt IS NULL) OR (demand_id IS NOT NULL AND demand_generation > 0 AND retry_attempt >= 0)), \n\tCONSTRAINT ck_analysis_runs_schema_version CHECK (schema_version = '2.0'), \n\tCONSTRAINT ck_analysis_runs_grouping_version CHECK (grouping_version = 'group-v1.1'), \n\tCONSTRAINT ck_analysis_runs_normalization_version CHECK (normalization_version = 'norm-v1.0'), \n\tCONSTRAINT ck_analysis_runs_symbol_inventory CHECK (symbol_inventory_version >= 0), \n\tCONSTRAINT ck_analysis_runs_quality_score CHECK (quality_score IS NULL OR (quality_score >= 0.0 AND quality_score <= 1.0)), \n\tCONSTRAINT ck_analysis_runs_status CHECK (status IN ('UPLOADED', 'VALIDATING', 'INSPECTED', 'MATCHING_SYMBOLS', 'WAITING_FOR_SYMBOLS', 'SYMBOLS_READY', 'QUEUED', 'ANALYZING', 'NORMALIZING', 'GROUPING', 'COMPLETE', 'PARTIAL', 'FAILED', 'REJECTED', 'CANCELLED', 'TIMEOUT', 'OOM')), \n\tCONSTRAINT ck_analysis_runs_idempotency_key CHECK (idempotency_key ~ '^[0-9a-fA-F]{64}$'), \n\tCONSTRAINT ck_analysis_runs_assembly_mode CHECK (assembly_mode = 'core-final'), \n\tCONSTRAINT ck_analysis_runs_winner_generation CHECK (winner_generation IS NULL OR winner_generation > 0), \n\tCONSTRAINT uq_analysis_runs_id_occurrence UNIQUE (id, occurrence_id), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id), \n\tFOREIGN KEY(demand_id) REFERENCES auto_analysis_demands (id), \n\tFOREIGN KEY(winner_attempt_id) REFERENCES task_intents (attempt_id)\n)",
    'CREATE INDEX ix_analysis_runs_occurrence_id_desc ON analysis_runs (occurrence_id, id DESC)',
    "CREATE TABLE analysis_execution_slots (\n\tdemand_id TEXT NOT NULL, \n\tworkspace_id TEXT NOT NULL, \n\tclaim_token TEXT NOT NULL, \n\towner_id TEXT NOT NULL, \n\tstate TEXT NOT NULL, \n\tlease_until TIMESTAMP WITH TIME ZONE, \n\trun_id TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (demand_id), \n\tCONSTRAINT uq_analysis_execution_slots_claim UNIQUE (claim_token), \n\tCONSTRAINT uq_analysis_execution_slots_run UNIQUE (run_id), \n\tCONSTRAINT ck_analysis_execution_slots_state CHECK (state IN ('planning','executing')), \n\tCONSTRAINT ck_analysis_execution_slots_binding CHECK ((state = 'planning' AND run_id IS NULL) OR (state = 'executing' AND run_id IS NOT NULL)), \n\tFOREIGN KEY(demand_id) REFERENCES auto_analysis_demands (id), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id), \n\tFOREIGN KEY(run_id) REFERENCES analysis_runs (id)\n)",
    'CREATE INDEX ix_analysis_execution_slots_lease ON analysis_execution_slots (state, lease_until)',
    "CREATE TABLE current_decisions (\n\tcandidate_run_id TEXT NOT NULL, \n\toccurrence_id TEXT NOT NULL, \n\tobserved_current_run_id TEXT, \n\trule_version TEXT NOT NULL, \n\tdecision TEXT NOT NULL, \n\treason TEXT NOT NULL, \n\tretry_recommended BOOLEAN NOT NULL, \n\tdifferences JSONB NOT NULL, \n\tcurrent_evidence JSONB, \n\tcandidate_evidence JSONB NOT NULL, \n\taudit_id TEXT, \n\taudit_sha256 CHAR(64), \n\texecution_attempt_id TEXT NOT NULL, \n\texecution_generation BIGINT NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (candidate_run_id), \n\tCONSTRAINT ck_current_decisions_rule CHECK (rule_version = 'evidence-v1'), \n\tCONSTRAINT ck_current_decisions_decision CHECK (decision IN ('promote','retain','incomparable','correct')), \n\tCONSTRAINT ck_current_decisions_generation CHECK (execution_generation > 0), \n\tCONSTRAINT uq_current_decisions_observation UNIQUE (candidate_run_id, observed_current_run_id, rule_version), \n\tFOREIGN KEY(candidate_run_id) REFERENCES analysis_runs (id), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id), \n\tFOREIGN KEY(observed_current_run_id) REFERENCES analysis_runs (id), \n\tFOREIGN KEY(execution_attempt_id) REFERENCES task_intents (attempt_id)\n)",
    'CREATE INDEX ix_current_decisions_occurrence_created ON current_decisions (occurrence_id, created_at)',
    "CREATE TABLE analysis_summaries (\n\tanalysis_run_id TEXT NOT NULL, \n\toccurrence_id TEXT NOT NULL, \n\texception_code TEXT, \n\texception_name TEXT, \n\taccess_type TEXT, \n\tcrash_address TEXT, \n\tcrashing_thread_id BIGINT, \n\tfault_module TEXT, \n\ttop_function TEXT, \n\ttop_source_file TEXT, \n\ttop_source_line INTEGER, \n\tsymbol_coverage REAL, \n\tunwind_reliability REAL, \n\tartifact_completeness REAL, \n\texact_fingerprint TEXT, \n\tfamily_fingerprint TEXT, \n\tcrashing_frames JSONB, \n\tcrash_type TEXT NOT NULL, \n\tPRIMARY KEY (analysis_run_id), \n\tCONSTRAINT ck_analysis_summaries_crash_type CHECK (crash_type IN ('crash', 'hang', 'unknown')), \n\tCONSTRAINT ck_analysis_summaries_symbol_coverage CHECK (symbol_coverage IS NULL OR (symbol_coverage >= 0.0 AND symbol_coverage <= 1.0)), \n\tCONSTRAINT ck_analysis_summaries_unwind_reliability CHECK (unwind_reliability IS NULL OR (unwind_reliability >= 0.0 AND unwind_reliability <= 1.0)), \n\tCONSTRAINT ck_analysis_summaries_artifact_completeness CHECK (artifact_completeness IS NULL OR (artifact_completeness >= 0.0 AND artifact_completeness <= 1.0)), \n\tFOREIGN KEY(analysis_run_id) REFERENCES analysis_runs (id), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id)\n)",
    'CREATE INDEX ix_analysis_summaries_exact_fingerprint ON analysis_summaries (exact_fingerprint)',
    'CREATE INDEX ix_analysis_summaries_exception_fault_module ON analysis_summaries (exception_code, fault_module)',
    "CREATE TABLE crash_groups (\n\tid TEXT NOT NULL, \n\tworkspace_id TEXT NOT NULL, \n\tgroup_type TEXT DEFAULT 'exact' NOT NULL, \n\tfingerprint TEXT NOT NULL, \n\trepresentative_run_id TEXT, \n\ttitle TEXT NOT NULL, \n\tstatus TEXT DEFAULT 'open' NOT NULL, \n\tfirst_seen TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen TIMESTAMP WITH TIME ZONE NOT NULL, \n\toccurrence_count INTEGER DEFAULT 0 NOT NULL, \n\towner TEXT, \n\tissue_url TEXT, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_crash_groups_workspace_type_fingerprint UNIQUE (workspace_id, group_type, fingerprint), \n\tCONSTRAINT ck_crash_groups_type CHECK (group_type = 'exact'), \n\tCONSTRAINT ck_crash_groups_status CHECK (status IN ('open', 'investigating', 'fixed', 'ignored')), \n\tCONSTRAINT ck_crash_groups_occurrence_count CHECK (occurrence_count >= 0), \n\tFOREIGN KEY(workspace_id) REFERENCES workspaces (id), \n\tFOREIGN KEY(representative_run_id) REFERENCES analysis_runs (id)\n)",
    "CREATE TABLE missing_symbol_occurrences (\n\tmissing_symbol_id TEXT NOT NULL, \n\toccurrence_id TEXT NOT NULL, \n\tworkspace_id TEXT NOT NULL, \n\tanalysis_run_id TEXT NOT NULL, \n\treason TEXT NOT NULL, \n\tcode_file TEXT, \n\tdebug_file TEXT, \n\tobserved_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (missing_symbol_id, occurrence_id), \n\tCONSTRAINT fk_missing_symbol_occurrences_symbol_workspace FOREIGN KEY(missing_symbol_id, workspace_id) REFERENCES missing_symbols (id, workspace_id), \n\tCONSTRAINT fk_missing_symbol_occurrences_occurrence_workspace FOREIGN KEY(occurrence_id, workspace_id) REFERENCES occurrences (id, workspace_id), \n\tCONSTRAINT fk_missing_symbol_occurrences_run_occurrence FOREIGN KEY(analysis_run_id, occurrence_id) REFERENCES analysis_runs (id, occurrence_id), \n\tCONSTRAINT ck_missing_symbol_occurrences_reason CHECK (reason IN ('missing_pe', 'missing_pdb', 'pdb_mismatch', 'pe_mismatch'))\n)",
    'CREATE INDEX ix_missing_symbol_occurrences_workspace ON missing_symbol_occurrences (workspace_id)',
    'CREATE INDEX ix_missing_symbol_occurrences_run ON missing_symbol_occurrences (analysis_run_id)',
    'CREATE INDEX ix_missing_symbol_occurrences_workspace_symbol_occurrence ON missing_symbol_occurrences (workspace_id, missing_symbol_id, occurrence_id)',
    'CREATE INDEX ix_missing_symbol_occurrences_occurrence ON missing_symbol_occurrences (occurrence_id)',
    "CREATE TABLE symbol_projection_states (\n\toccurrence_id TEXT NOT NULL, \n\tworkspace_id TEXT NOT NULL, \n\tanalysis_run_id TEXT NOT NULL, \n\tidentity_digest CHAR(64) NOT NULL, \n\tmissing_count INTEGER NOT NULL, \n\tsource TEXT NOT NULL, \n\tprojected_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (occurrence_id), \n\tCONSTRAINT fk_symbol_projection_states_occurrence_workspace FOREIGN KEY(occurrence_id, workspace_id) REFERENCES occurrences (id, workspace_id), \n\tCONSTRAINT fk_symbol_projection_states_run_occurrence FOREIGN KEY(analysis_run_id, occurrence_id) REFERENCES analysis_runs (id, occurrence_id), \n\tCONSTRAINT ck_symbol_projection_states_missing_count CHECK (missing_count >= 0), \n\tCONSTRAINT ck_symbol_projection_states_source CHECK (source = 'promotion')\n)",
    'CREATE INDEX ix_symbol_projection_states_workspace_run ON symbol_projection_states (workspace_id, analysis_run_id)',
    "CREATE TABLE result_reviews (\n\tid TEXT NOT NULL, \n\toccurrence_id TEXT NOT NULL, \n\tcurrent_run_id TEXT NOT NULL, \n\tcandidate_run_id TEXT NOT NULL, \n\tidempotency_key TEXT NOT NULL, \n\trequest_sha256 CHAR(64) NOT NULL, \n\trequest JSONB NOT NULL, \n\taudit_object_key TEXT NOT NULL, \n\taudit_sha256 CHAR(64) NOT NULL, \n\tcause TEXT NOT NULL, \n\tdecision TEXT NOT NULL, \n\treason TEXT NOT NULL, \n\tcurrent_evidence JSONB NOT NULL, \n\tcandidate_evidence JSONB NOT NULL, \n\tdifferences JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_result_reviews_request UNIQUE (occurrence_id, idempotency_key), \n\tCONSTRAINT ck_result_reviews_distinct CHECK (current_run_id <> candidate_run_id), \n\tCONSTRAINT ck_result_reviews_cause CHECK (cause IN ('engine_upgrade','role_change','evidence_correction')), \n\tCONSTRAINT ck_result_reviews_decision CHECK (decision IN ('promote','retain','incomparable','correct')), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id), \n\tFOREIGN KEY(current_run_id) REFERENCES analysis_runs (id), \n\tFOREIGN KEY(candidate_run_id) REFERENCES current_decisions (candidate_run_id)\n)",
    'CREATE INDEX ix_result_reviews_history ON result_reviews (occurrence_id, created_at, id)',
    'CREATE TABLE group_memberships (\n\toccurrence_id TEXT NOT NULL, \n\tgroup_id TEXT NOT NULL, \n\tanalysis_run_id TEXT NOT NULL, \n\tsimilarity REAL DEFAULT 1.0 NOT NULL, \n\tgrouping_evidence_json JSONB NOT NULL, \n\tassigned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (occurrence_id), \n\tCONSTRAINT ck_group_memberships_similarity CHECK (similarity = 1.0), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id), \n\tFOREIGN KEY(group_id) REFERENCES crash_groups (id), \n\tFOREIGN KEY(analysis_run_id) REFERENCES analysis_runs (id)\n)',
    "CREATE TABLE group_membership_history (\n\tid BIGSERIAL NOT NULL, \n\toccurrence_id TEXT NOT NULL, \n\tprevious_group_id TEXT, \n\tgroup_id TEXT, \n\tanalysis_run_id TEXT NOT NULL, \n\taction TEXT NOT NULL, \n\tsimilarity REAL DEFAULT 1.0 NOT NULL, \n\tgrouping_evidence_json JSONB NOT NULL, \n\trecorded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT ck_group_membership_history_action CHECK (action IN ('assign', 'move', 'unclassify')), \n\tCONSTRAINT ck_group_membership_history_similarity CHECK (similarity = 1.0), \n\tFOREIGN KEY(occurrence_id) REFERENCES occurrences (id), \n\tFOREIGN KEY(previous_group_id) REFERENCES crash_groups (id), \n\tFOREIGN KEY(group_id) REFERENCES crash_groups (id), \n\tFOREIGN KEY(analysis_run_id) REFERENCES analysis_runs (id)\n)",
    'CREATE INDEX ix_group_membership_history_occurrence_recorded ON group_membership_history (occurrence_id, recorded_at)',
    'ALTER TABLE occurrences ADD CONSTRAINT fk_occurrences_current_run_id FOREIGN KEY(current_run_id) REFERENCES analysis_runs (id)',
    'INSERT INTO catalog_watermark (id, revision) VALUES (1, 0)',
    "CREATE FUNCTION reject_immutable_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'immutable history cannot be changed'; END; $$",
    'CREATE TRIGGER result_reviews_immutable BEFORE UPDATE OR DELETE ON result_reviews FOR EACH ROW EXECUTE FUNCTION reject_immutable_history_mutation()',
    'CREATE TRIGGER analysis_demand_restarts_immutable BEFORE UPDATE OR DELETE ON analysis_demand_restarts FOR EACH ROW EXECUTE FUNCTION reject_immutable_history_mutation()',
    'CREATE TRIGGER occurrence_version_audits_immutable BEFORE UPDATE OR DELETE ON occurrence_version_audits FOR EACH ROW EXECUTE FUNCTION reject_immutable_history_mutation()',
    'CREATE TRIGGER catalog_files_immutable BEFORE UPDATE OR DELETE ON catalog_files FOR EACH ROW EXECUTE FUNCTION reject_immutable_history_mutation()',
]

def upgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        raise RuntimeError("The deployment baseline requires PostgreSQL 15+")
    for statement in STATEMENTS:
        op.execute(statement)

def downgrade() -> None:
    raise RuntimeError("Restore the complete previous deployment and its backup; reverse migration is unsupported")
